"""create pitch sequence feature table

Revision ID: 128f06e10c00
Revises: 333d4a370cfa
Create Date: 2026-07-30 04:40:31.589788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '128f06e10c00'
down_revision: Union[str, Sequence[str], None] = '333d4a370cfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitch_sequence_features',
    sa.Column('feature_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('game_pk', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('at_bat_number', sa.Integer(), nullable=False),
    sa.Column('pitch_number', sa.Integer(), nullable=False),
    sa.Column('pitcher_id', sa.Integer(), nullable=False),
    sa.Column('batter_id', sa.Integer(), nullable=False),
    sa.Column('pitcher_hand', sa.String(length=5), nullable=True),
    sa.Column('batter_side', sa.String(length=5), nullable=True),
    sa.Column('inning', sa.Integer(), nullable=True),
    sa.Column('inning_half', sa.String(length=10), nullable=True),
    sa.Column('outs_before_pitch', sa.Integer(), nullable=True),
    sa.Column('balls_before_pitch', sa.Integer(), nullable=False),
    sa.Column('strikes_before_pitch', sa.Integer(), nullable=False),
    sa.Column('previous_pitch_type', sa.String(length=10), nullable=True),
    sa.Column('previous_pitch_zone', sa.String(length=30), nullable=True),
    sa.Column('previous_pitch_result', sa.String(length=100), nullable=True),
    sa.Column('second_previous_pitch_type', sa.String(length=10), nullable=True),
    sa.Column('second_previous_pitch_zone', sa.String(length=30), nullable=True),
    sa.Column('third_previous_pitch_type', sa.String(length=10), nullable=True),
    sa.Column('runner_on_first', sa.Boolean(), nullable=False),
    sa.Column('runner_on_second', sa.Boolean(), nullable=False),
    sa.Column('runner_on_third', sa.Boolean(), nullable=False),
    sa.Column('target_pitch_type', sa.String(length=10), nullable=False),
    sa.Column('target_pitch_name', sa.String(length=100), nullable=True),
    sa.Column('target_pitch_zone', sa.String(length=30), nullable=True),
    sa.Column('target_plate_x', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('target_plate_z', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('target_release_speed', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('target_description', sa.String(length=100), nullable=True),
    sa.Column('target_is_ball', sa.Boolean(), nullable=True),
    sa.Column('target_is_strike', sa.Boolean(), nullable=True),
    sa.Column('target_is_in_play', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batter_id'], ['players.player_id'], name=op.f('fk_pitch_sequence_features_batter_id_players')),
    sa.ForeignKeyConstraint(['game_pk'], ['games.game_pk'], name=op.f('fk_pitch_sequence_features_game_pk_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pitcher_id'], ['players.player_id'], name=op.f('fk_pitch_sequence_features_pitcher_id_players')),
    sa.PrimaryKeyConstraint('feature_id', name=op.f('pk_pitch_sequence_features')),
    sa.UniqueConstraint('game_pk', 'at_bat_number', 'pitch_number', name='uq_pitch_sequence_game_at_bat_pitch')
    )
    op.create_index('ix_pitch_sequence_batter', 'pitch_sequence_features', ['batter_id'], unique=False)
    op.create_index('ix_pitch_sequence_count', 'pitch_sequence_features', ['balls_before_pitch', 'strikes_before_pitch'], unique=False)
    op.create_index('ix_pitch_sequence_game_date', 'pitch_sequence_features', ['game_date'], unique=False)
    op.create_index('ix_pitch_sequence_pitcher', 'pitch_sequence_features', ['pitcher_id'], unique=False)
    op.create_index('ix_pitch_sequence_season', 'pitch_sequence_features', ['season'], unique=False)
    op.create_index('ix_pitch_sequence_target_type', 'pitch_sequence_features', ['target_pitch_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pitch_sequence_target_type', table_name='pitch_sequence_features')
    op.drop_index('ix_pitch_sequence_season', table_name='pitch_sequence_features')
    op.drop_index('ix_pitch_sequence_pitcher', table_name='pitch_sequence_features')
    op.drop_index('ix_pitch_sequence_game_date', table_name='pitch_sequence_features')
    op.drop_index('ix_pitch_sequence_count', table_name='pitch_sequence_features')
    op.drop_index('ix_pitch_sequence_batter', table_name='pitch_sequence_features')
    op.drop_table('pitch_sequence_features')
    # ### end Alembic commands ###
