"""create pitch sequence feature table

Revision ID: 18e1f144188c
Revises: 128f06e10c00
Create Date: 2026-07-30 04:58:21.447143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18e1f144188c'
down_revision: Union[str, Sequence[str], None] = '128f06e10c00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pitch_sequence_batter'), table_name='pitch_sequence_features')
    op.drop_index(op.f('ix_pitch_sequence_pitcher'), table_name='pitch_sequence_features')
    op.drop_index(op.f('ix_pitch_sequence_target_type'), table_name='pitch_sequence_features')
    op.create_index('ix_pitch_sequence_batter_id', 'pitch_sequence_features', ['batter_id'], unique=False)
    op.create_index('ix_pitch_sequence_pitcher_id', 'pitch_sequence_features', ['pitcher_id'], unique=False)
    op.create_index('ix_pitch_sequence_target_pitch_type', 'pitch_sequence_features', ['target_pitch_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pitch_sequence_target_pitch_type', table_name='pitch_sequence_features')
    op.drop_index('ix_pitch_sequence_pitcher_id', table_name='pitch_sequence_features')
    op.drop_index('ix_pitch_sequence_batter_id', table_name='pitch_sequence_features')
    op.create_index(op.f('ix_pitch_sequence_target_type'), 'pitch_sequence_features', ['target_pitch_type'], unique=False)
    op.create_index(op.f('ix_pitch_sequence_pitcher'), 'pitch_sequence_features', ['pitcher_id'], unique=False)
    op.create_index(op.f('ix_pitch_sequence_batter'), 'pitch_sequence_features', ['batter_id'], unique=False)
    # ### end Alembic commands ###
