"""expand game schedule fields

Revision ID: 248f4027565a
Revises: ac823ca0577b
Create Date: 2026-07-30 02:32:23.097156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '248f4027565a'
down_revision: Union[str, Sequence[str], None] = 'ac823ca0577b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('games', sa.Column('detailed_status', sa.String(length=100), nullable=True))
    op.add_column('games', sa.Column('abstract_status', sa.String(length=50), nullable=True))
    op.add_column('games', sa.Column('doubleheader', sa.String(length=20), nullable=True))
    op.add_column('games', sa.Column('game_number', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('home_probable_pitcher_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_probable_pitcher_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('inning', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('inning_half', sa.String(length=20), nullable=True))
    op.create_index('ix_games_away_team_id', 'games', ['away_team_id'], unique=False)
    op.create_index('ix_games_home_team_id', 'games', ['home_team_id'], unique=False)
    op.create_index('ix_games_status', 'games', ['status'], unique=False)
    op.create_foreign_key(op.f('fk_games_away_probable_pitcher_id_players'), 'games', 'players', ['away_probable_pitcher_id'], ['player_id'])
    op.create_foreign_key(op.f('fk_games_home_probable_pitcher_id_players'), 'games', 'players', ['home_probable_pitcher_id'], ['player_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_games_home_probable_pitcher_id_players'), 'games', type_='foreignkey')
    op.drop_constraint(op.f('fk_games_away_probable_pitcher_id_players'), 'games', type_='foreignkey')
    op.drop_index('ix_games_status', table_name='games')
    op.drop_index('ix_games_home_team_id', table_name='games')
    op.drop_index('ix_games_away_team_id', table_name='games')
    op.drop_column('games', 'inning_half')
    op.drop_column('games', 'inning')
    op.drop_column('games', 'away_probable_pitcher_id')
    op.drop_column('games', 'home_probable_pitcher_id')
    op.drop_column('games', 'game_number')
    op.drop_column('games', 'doubleheader')
    op.drop_column('games', 'abstract_status')
    op.drop_column('games', 'detailed_status')
    op.drop_column('games', 'scheduled_start')
    # ### end Alembic commands ###
