"""expand pitch ingestion fields

Revision ID: 333d4a370cfa
Revises: 248f4027565a
Create Date: 2026-07-30 02:45:15.484253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '333d4a370cfa'
down_revision: Union[str, Sequence[str], None] = '248f4027565a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('pitches_collected', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('games', sa.Column('pitch_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('games', sa.Column('pitches_collected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('games', sa.Column('pitch_collection_error', sa.Text(), nullable=True))
    op.add_column('pitches', sa.Column('plate_appearance_number', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('event_type', sa.String(length=100), nullable=True))
    op.add_column('pitches', sa.Column('is_pitch', sa.Boolean(), nullable=False))
    op.add_column('pitches', sa.Column('is_ball', sa.Boolean(), nullable=True))
    op.add_column('pitches', sa.Column('is_strike', sa.Boolean(), nullable=True))
    op.add_column('pitches', sa.Column('is_in_play', sa.Boolean(), nullable=True))
    op.add_column('pitches', sa.Column('hit_location', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('trajectory', sa.String(length=50), nullable=True))
    op.add_column('pitches', sa.Column('hardness', sa.String(length=50), nullable=True))
    op.add_column('pitches', sa.Column('home_score', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('away_score', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('pitches', 'pitch_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('pitches', 'release_speed',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=7, scale=3),
               existing_nullable=True)
    op.alter_column('pitches', 'effective_speed',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=7, scale=3),
               existing_nullable=True)
    op.alter_column('pitches', 'release_extension',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=7, scale=3),
               existing_nullable=True)
    op.alter_column('pitches', 'release_pos_x',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               type_=sa.Numeric(precision=9, scale=4),
               existing_nullable=True)
    op.alter_column('pitches', 'release_pos_y',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               type_=sa.Numeric(precision=9, scale=4),
               existing_nullable=True)
    op.alter_column('pitches', 'release_pos_z',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               type_=sa.Numeric(precision=9, scale=4),
               existing_nullable=True)
    op.alter_column('pitches', 'plate_x',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               type_=sa.Numeric(precision=9, scale=4),
               existing_nullable=True)
    op.alter_column('pitches', 'plate_z',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               type_=sa.Numeric(precision=9, scale=4),
               existing_nullable=True)
    op.alter_column('pitches', 'strike_zone_top',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               type_=sa.Numeric(precision=9, scale=4),
               existing_nullable=True)
    op.alter_column('pitches', 'strike_zone_bottom',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               type_=sa.Numeric(precision=9, scale=4),
               existing_nullable=True)
    op.alter_column('pitches', 'pfx_x',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               type_=sa.Numeric(precision=9, scale=4),
               existing_nullable=True)
    op.alter_column('pitches', 'pfx_z',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               type_=sa.Numeric(precision=9, scale=4),
               existing_nullable=True)
    op.alter_column('pitches', 'launch_speed',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=7, scale=3),
               existing_nullable=True)
    op.alter_column('pitches', 'launch_angle',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=7, scale=3),
               existing_nullable=True)
    op.alter_column('pitches', 'hit_distance',
               existing_type=sa.NUMERIC(precision=7, scale=2),
               type_=sa.Numeric(precision=8, scale=3),
               existing_nullable=True)
    op.alter_column('pitches', 'estimated_batting_average',
               existing_type=sa.NUMERIC(precision=6, scale=5),
               type_=sa.Numeric(precision=8, scale=6),
               existing_nullable=True)
    op.alter_column('pitches', 'estimated_woba',
               existing_type=sa.NUMERIC(precision=6, scale=5),
               type_=sa.Numeric(precision=8, scale=6),
               existing_nullable=True)
    op.alter_column('pitches', 'estimated_slugging',
               existing_type=sa.NUMERIC(precision=6, scale=5),
               type_=sa.Numeric(precision=8, scale=6),
               existing_nullable=True)
    op.create_index('ix_pitches_game_pk', 'pitches', ['game_pk'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pitches_game_pk', table_name='pitches')
    op.alter_column('pitches', 'estimated_slugging',
               existing_type=sa.Numeric(precision=8, scale=6),
               type_=sa.NUMERIC(precision=6, scale=5),
               existing_nullable=True)
    op.alter_column('pitches', 'estimated_woba',
               existing_type=sa.Numeric(precision=8, scale=6),
               type_=sa.NUMERIC(precision=6, scale=5),
               existing_nullable=True)
    op.alter_column('pitches', 'estimated_batting_average',
               existing_type=sa.Numeric(precision=8, scale=6),
               type_=sa.NUMERIC(precision=6, scale=5),
               existing_nullable=True)
    op.alter_column('pitches', 'hit_distance',
               existing_type=sa.Numeric(precision=8, scale=3),
               type_=sa.NUMERIC(precision=7, scale=2),
               existing_nullable=True)
    op.alter_column('pitches', 'launch_angle',
               existing_type=sa.Numeric(precision=7, scale=3),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('pitches', 'launch_speed',
               existing_type=sa.Numeric(precision=7, scale=3),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('pitches', 'pfx_z',
               existing_type=sa.Numeric(precision=9, scale=4),
               type_=sa.NUMERIC(precision=8, scale=4),
               existing_nullable=True)
    op.alter_column('pitches', 'pfx_x',
               existing_type=sa.Numeric(precision=9, scale=4),
               type_=sa.NUMERIC(precision=8, scale=4),
               existing_nullable=True)
    op.alter_column('pitches', 'strike_zone_bottom',
               existing_type=sa.Numeric(precision=9, scale=4),
               type_=sa.NUMERIC(precision=8, scale=4),
               existing_nullable=True)
    op.alter_column('pitches', 'strike_zone_top',
               existing_type=sa.Numeric(precision=9, scale=4),
               type_=sa.NUMERIC(precision=8, scale=4),
               existing_nullable=True)
    op.alter_column('pitches', 'plate_z',
               existing_type=sa.Numeric(precision=9, scale=4),
               type_=sa.NUMERIC(precision=8, scale=4),
               existing_nullable=True)
    op.alter_column('pitches', 'plate_x',
               existing_type=sa.Numeric(precision=9, scale=4),
               type_=sa.NUMERIC(precision=8, scale=4),
               existing_nullable=True)
    op.alter_column('pitches', 'release_pos_z',
               existing_type=sa.Numeric(precision=9, scale=4),
               type_=sa.NUMERIC(precision=8, scale=4),
               existing_nullable=True)
    op.alter_column('pitches', 'release_pos_y',
               existing_type=sa.Numeric(precision=9, scale=4),
               type_=sa.NUMERIC(precision=8, scale=4),
               existing_nullable=True)
    op.alter_column('pitches', 'release_pos_x',
               existing_type=sa.Numeric(precision=9, scale=4),
               type_=sa.NUMERIC(precision=8, scale=4),
               existing_nullable=True)
    op.alter_column('pitches', 'release_extension',
               existing_type=sa.Numeric(precision=7, scale=3),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('pitches', 'effective_speed',
               existing_type=sa.Numeric(precision=7, scale=3),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('pitches', 'release_speed',
               existing_type=sa.Numeric(precision=7, scale=3),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('pitches', 'pitch_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('pitches', 'updated_at')
    op.drop_column('pitches', 'away_score')
    op.drop_column('pitches', 'home_score')
    op.drop_column('pitches', 'hardness')
    op.drop_column('pitches', 'trajectory')
    op.drop_column('pitches', 'hit_location')
    op.drop_column('pitches', 'is_in_play')
    op.drop_column('pitches', 'is_strike')
    op.drop_column('pitches', 'is_ball')
    op.drop_column('pitches', 'is_pitch')
    op.drop_column('pitches', 'event_type')
    op.drop_column('pitches', 'plate_appearance_number')
    op.drop_column('games', 'pitch_collection_error')
    op.drop_column('games', 'pitches_collected_at')
    op.drop_column('games', 'pitch_count')
    op.drop_column('games', 'pitches_collected')
    # ### end Alembic commands ###
