"""link teams to current parks

Revision ID: 744726403738
Revises: b6e6f6ed04e1
Create Date: 2026-07-30 02:13:49.149009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '744726403738'
down_revision: Union[str, Sequence[str], None] = 'b6e6f6ed04e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('current_park_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_teams_current_park_id_parks'), 'teams', 'parks', ['current_park_id'], ['park_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_teams_current_park_id_parks'), 'teams', type_='foreignkey')
    op.drop_column('teams', 'current_park_id')
    # ### end Alembic commands ###
