"""expand player roster fields

Revision ID: ac823ca0577b
Revises: 744726403738
Create Date: 2026-07-30 02:22:17.771544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac823ca0577b'
down_revision: Union[str, Sequence[str], None] = '744726403738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('players', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('players', sa.Column('use_name', sa.String(length=100), nullable=True))
    op.add_column('players', sa.Column('position_name', sa.String(length=100), nullable=True))
    op.add_column('players', sa.Column('position_type', sa.String(length=50), nullable=True))
    op.add_column('players', sa.Column('mlb_debut_date', sa.Date(), nullable=True))
    op.add_column('players', sa.Column('height', sa.String(length=20), nullable=True))
    op.add_column('players', sa.Column('weight', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('jersey_number', sa.String(length=10), nullable=True))
    op.add_column('players', sa.Column('roster_status', sa.String(length=50), nullable=True))
    op.add_column('players', sa.Column('last_roster_check_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_players_active', 'players', ['active'], unique=False)
    op.create_index('ix_players_current_team_id', 'players', ['current_team_id'], unique=False)
    op.create_index('ix_players_full_name', 'players', ['full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_players_full_name', table_name='players')
    op.drop_index('ix_players_current_team_id', table_name='players')
    op.drop_index('ix_players_active', table_name='players')
    op.drop_column('players', 'last_roster_check_at')
    op.drop_column('players', 'roster_status')
    op.drop_column('players', 'jersey_number')
    op.drop_column('players', 'weight')
    op.drop_column('players', 'height')
    op.drop_column('players', 'mlb_debut_date')
    op.drop_column('players', 'position_type')
    op.drop_column('players', 'position_name')
    op.drop_column('players', 'use_name')
    op.drop_column('players', 'last_name')
    op.drop_column('players', 'first_name')
    # ### end Alembic commands ###
