"""create core baseball tables

Revision ID: b6e6f6ed04e1
Revises: 
Create Date: 2026-07-30 01:58:09.472634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e6f6ed04e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_runs',
    sa.Column('collection_run_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('collector_name', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('requested_start_date', sa.Date(), nullable=True),
    sa.Column('requested_end_date', sa.Date(), nullable=True),
    sa.Column('records_read', sa.Integer(), nullable=False),
    sa.Column('records_inserted', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_rejected', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('collection_run_id', name=op.f('pk_collection_runs'))
    )
    op.create_table('parks',
    sa.Column('park_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('time_zone', sa.String(length=100), nullable=True),
    sa.Column('elevation_feet', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('park_id', name=op.f('pk_parks'))
    )
    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=True),
    sa.Column('league_name', sa.String(length=50), nullable=True),
    sa.Column('division_name', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('team_id', name=op.f('pk_teams'))
    )
    op.create_table('games',
    sa.Column('game_pk', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('park_id', sa.Integer(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('day_night', sa.String(length=10), nullable=True),
    sa.Column('temperature_f', sa.Integer(), nullable=True),
    sa.Column('wind_speed_mph', sa.Integer(), nullable=True),
    sa.Column('wind_direction', sa.String(length=100), nullable=True),
    sa.Column('weather_condition', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.team_id'], name=op.f('fk_games_away_team_id_teams')),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.team_id'], name=op.f('fk_games_home_team_id_teams')),
    sa.ForeignKeyConstraint(['park_id'], ['parks.park_id'], name=op.f('fk_games_park_id_parks')),
    sa.PrimaryKeyConstraint('game_pk', name=op.f('pk_games'))
    )
    op.create_index('ix_games_game_date', 'games', ['game_date'], unique=False)
    op.create_index('ix_games_season', 'games', ['season'], unique=False)
    op.create_table('players',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('primary_position', sa.String(length=10), nullable=True),
    sa.Column('bats', sa.String(length=5), nullable=True),
    sa.Column('throws', sa.String(length=5), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('current_team_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_team_id'], ['teams.team_id'], name=op.f('fk_players_current_team_id_teams')),
    sa.PrimaryKeyConstraint('player_id', name=op.f('pk_players'))
    )
    op.create_table('pitches',
    sa.Column('pitch_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('game_pk', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('at_bat_number', sa.Integer(), nullable=False),
    sa.Column('pitch_number', sa.Integer(), nullable=False),
    sa.Column('inning', sa.Integer(), nullable=True),
    sa.Column('inning_half', sa.String(length=10), nullable=True),
    sa.Column('outs', sa.Integer(), nullable=True),
    sa.Column('balls', sa.Integer(), nullable=True),
    sa.Column('strikes', sa.Integer(), nullable=True),
    sa.Column('pitcher_id', sa.Integer(), nullable=False),
    sa.Column('batter_id', sa.Integer(), nullable=False),
    sa.Column('pitch_type', sa.String(length=10), nullable=True),
    sa.Column('pitch_name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('event', sa.String(length=100), nullable=True),
    sa.Column('release_speed', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('effective_speed', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('release_spin_rate', sa.Integer(), nullable=True),
    sa.Column('release_extension', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('release_pos_x', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('release_pos_y', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('release_pos_z', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('plate_x', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('plate_z', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('strike_zone_top', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('strike_zone_bottom', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('pfx_x', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('pfx_z', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('launch_speed', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('launch_angle', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('hit_distance', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('estimated_batting_average', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('estimated_woba', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('estimated_slugging', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('zone', sa.Integer(), nullable=True),
    sa.Column('type_code', sa.String(length=5), nullable=True),
    sa.Column('runner_on_first', sa.Boolean(), nullable=False),
    sa.Column('runner_on_second', sa.Boolean(), nullable=False),
    sa.Column('runner_on_third', sa.Boolean(), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batter_id'], ['players.player_id'], name=op.f('fk_pitches_batter_id_players')),
    sa.ForeignKeyConstraint(['game_pk'], ['games.game_pk'], name=op.f('fk_pitches_game_pk_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pitcher_id'], ['players.player_id'], name=op.f('fk_pitches_pitcher_id_players')),
    sa.PrimaryKeyConstraint('pitch_id', name=op.f('pk_pitches')),
    sa.UniqueConstraint('game_pk', 'at_bat_number', 'pitch_number', name='uq_pitches_game_at_bat_pitch')
    )
    op.create_index('ix_pitches_batter_id', 'pitches', ['batter_id'], unique=False)
    op.create_index('ix_pitches_game_date', 'pitches', ['game_date'], unique=False)
    op.create_index('ix_pitches_pitch_type', 'pitches', ['pitch_type'], unique=False)
    op.create_index('ix_pitches_pitcher_id', 'pitches', ['pitcher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pitches_pitcher_id', table_name='pitches')
    op.drop_index('ix_pitches_pitch_type', table_name='pitches')
    op.drop_index('ix_pitches_game_date', table_name='pitches')
    op.drop_index('ix_pitches_batter_id', table_name='pitches')
    op.drop_table('pitches')
    op.drop_table('players')
    op.drop_index('ix_games_season', table_name='games')
    op.drop_index('ix_games_game_date', table_name='games')
    op.drop_table('games')
    op.drop_table('teams')
    op.drop_table('parks')
    op.drop_table('collection_runs')
    # ### end Alembic commands ###
